### ISSUE TITLE
boxxy scan doesn't write anything in the config file

### ISSUE THREAD

**Issue by hazelnot** [queer/boxxy#200]
I ran `boxxy scan` to auto-generate a config as a base, and at the end it output `INFO  boxxy > put relevant rules in your config file: $HOME/.config/boxxy/boxxy.yaml`, but the boxxy config folder stays empty.

I even tried to create `boxxy.yaml` myself, but the file is still empty after running `boxxy scan` a second time.

I'm on Arch Linux, using the version packaged with the distro (0.8.4).

**Comment by queer** [comment]
It does not fill in the config file for you; you have to choose the rules you want added to put into your config. This is because it might be disruptive to some applications, you might not want everything moved out of your homedir, etc. The message can likely be improved; the “put rules in …” message is an instruction to the end user, not an action taken by the tool.

**Comment by hazelnot** [comment]
Ah fair

I ended up pasting the config myself, but yeah the language in the readme is confusing, especially when the message at the end says "put relevant rules in your config file" which I interpreted as the program saying "here's what I did" 😅

**Comment by queer** [comment]
I'll leave this open for now so I can remember to update this message.
