### ISSUE TITLE
Could this be run inside Docker?

### ISSUE THREAD

**Issue by gaby** [queer/boxxy#43]
I've been wondering if it would be possible to run `boxxy` inside a Docker container as an extra layer.

I think it would be useful to force tools to write data inside a container to a tmpfs, etc.

**Comment by queer** [comment]
You need to either have `CAP_SYS_ADMIN` inside the container, or run the Docker container with `--security-opt seccomp=unconfined` (or other seccomp profile). This is because boxxy uses Linux namespaces and nesting them with Docker is complicated. There may be a better way to do this, I'm just not sure. See also:

- https://github.com/moby/moby/issues/43086
- https://github.com/apache/camel-k/issues/1580#issuecomment-655514148
- https://github.com/genuinetools/img/issues/305#issuecomment-750373387
